### PR TITLE
Consider boolean parameter in getStringId method

### PR DESCRIPTION
**Pull request by Ali-RS**
In case it could not find string id it will create it only if boolean parameter is set to true.

### CODE REVIEW

**Comment by Ali-RS** [comment]
Hi @pspeed42 , If there is any problem with this commit, please mention it.

**Comment by pspeed42** [comment]
Because of the unnecessary formatting changes I was just going to do the one line change myself... but I haven't gotten around to it yet.

**Comment by Ali-RS** [comment]
Okay.

**Comment by pspeed42** [comment]
If you get to resubmitting it without the formatting changes before I do then I will just merge your request.  Normally I wouldn't care but it's otherwise only a one line change... so making the formatting inconsistent for a handful of lines because of that doesn't seem worth it.  (Especially since add=false has few real use-cases anyway.)

**Pull request closed without merging**
