### PR TITLE
Add EntityData.removeComponents()

### PR DESCRIPTION
**Pull request by Ali-RS**
Solves #28 

I needed to bump the language to java 8 to be able to use the java 8 "extension/default method on interface" feature. 

Forum topic:
https://hub.jmonkeyengine.org/t/suggestion-of-adding-ed-removecomponents/46620

### CODE REVIEW

**Comment by pspeed42** [comment]
Would prefer not having "real code" hidden in the interface.  This is a Java feature that I think is often abused.  It's one thing when the methods are empty or throw UnsupportedOperationException but to actually implement real "could someday have bugs" style code is bad to me.

I think most custom implementations will extend DefaultEntityData.  So it's probably fine to put it there... and in that case we can leave the interface method unimplemented so anyone not extending DefaultEntityData will  know immediately that they have work to do.

**Comment by Ali-RS** [comment]
Ok, I applied the requested changes.

**Comment by Ali-RS** [comment]
Bump :)

**Comment by pspeed42** [comment]
Sorry this took me so long.  I'm finally giving my open source projects some TLC after this last Mythruna milestone.

**Pull request merged**
